services:
  db:
    image: postgres:15-alpine
    container_name: pilateka_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi_data:/var/lib/postgresql/data
    networks:
      - pilateka_network

  backend:
    container_name: pilateka_backend
    build:
      context: ./backend
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
    ports:
      - "13377:1337"
    depends_on:
      - db
    networks:
      - pilateka_network

  frontend:
    container_name: pilateka_frontend
    build:
      context: ./frontend
      args:
        STRAPI_URL: http://backend:1337
    restart: always
    ports:
      - "4321:80"
    depends_on:
      - backend
    networks:
      - pilateka_network

networks:
  pilateka_network:
    driver: bridge

volumes:
  strapi_data:
